version: "3"

services:

  db:
    image: postgres:16-alpine
    container_name: postgres_db
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $POSTGRES_USER" ]
      interval: 5s
      timeout: 5s
      retries: 5


  redis:
    image: redis
    restart: on-failure
    ports:
      - "6379:6379"

  app:
    build: .
    container_name: habit_app
    tty: true
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    env_file:
      - .env
    ports:
      - '8000:8000'
    depends_on:
      db:
        condition: service_healthy

  celery:
    build: .
    tty: true
    command: celery -A config worker -l INFO -P eventlet
    restart: on-failure
    volumes:
      - .:/code
    depends_on:
      - redis
      - app
      - db
    env_file:
      - .env

  celery_beat:
    build: .
    tty: true
    command: celery -A config beat -l INFO -S django
    restart: on-failure
    volumes:
      - .:/code
    depends_on:
      - db
      - redis
      - app
    env_file:
      - .env

volumes:
  pg_data: